Заменить Http Service на Spring feign
artsiom-kotau/stock-feed pull request #10
Opened 2021-05-04 11:41 UTC by s-konanau

2021-05-04 12:42 UTC, artsiom-kotau requested changes

2021-05-04 12:42 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/service/feign/FinnhubApiWithFeign.java
> +    StockEntity[] getStocks(@RequestParam String exchange);
почему нельзя вернуть сразу List ?

2021-05-05 08:10 UTC, s-konanau commented
не получается, из-за 'class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class'

2021-05-05 08:10 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/service/feign/FinnhubApiWithFeign.java
> +    StockEntity[] getStocks(@RequestParam String exchange);
не получается, из-за 'class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class'

2021-05-05 11:24 UTC, merged