Authentication
artsiom-kotau/stock-feed pull request #11
Opened 2021-05-19 12:53 UTC by s-konanau

2021-05-24 10:29 UTC, artsiom-kotau requested changes

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    public List<AccountEntity> getAll() {
Нужно использовать DTO паттерн, получается ты тут вылаживаешь всю инфу о пользователе: например пароль

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    @GetMapping
для чего этот урл?

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    public ResponseEntity<String> signUp(@RequestParam String email, @RequestParam String password) {
Используй RequestBody с классом User, в котором будет необходимый для регистрации набор полей

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("account created");
можно просто возвращать код 202, тогда ResponseEntity не нужен будет

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    private final ObjectSerialization serialization;
Spring сам всё сериализует, это лишнее

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/ControllerExceptionHandler.java
> +    @ResponseBody
Лучше сделать какой-то класс типа ErrorResponse
где ты можешь формализировать набор полей для описания ошибки

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/entity/AccountEntity.java
> +    public String toString() {
ну тут перебор, такой toString нам не нужен

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public Account create(String email, String password) {
@Transactional

2021-05-24 10:29 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public AccountEntity getAccountByEmail(String email) throws SearchException {
Сервис может использоваться в логике в дальнейшем и ориентироваться на Exception не самая лучшая идея.
Используй Optional
экзепшен выбрасывай в контроллере

2021-05-24 10:38 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("account created");
только код, без какого-либо сообщения?

2021-05-24 10:41 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    private final ObjectSerialization serialization;
ну у меня же особая сереализация, gson и имена полей не совпадают, это надо наверное спринг настроить чтобы он подхватывал мои настройки и библиотеку. Или переходить на стандартный парсер в спринге?

2021-05-24 10:45 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/entity/AccountEntity.java
> +    public String toString() {
такой это тот который изменяет строку из суперкласса, или который выводит id, или что ещё и пароль выводится, или он просто написан некрасиво?

2021-05-24 10:45 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    private final ObjectSerialization serialization;
а почему ты решил gson использовать?
для этого есть паттерн дто, т.е. ты инициализируешь DTO полями из энтити

2021-05-24 10:45 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("account created");
пока да

2021-05-24 10:46 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/entity/AccountEntity.java
> +    public String toString() {
как ты вообще используешь его? для дебага?

2021-05-24 10:47 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    @GetMapping
возвращает аккаунт по email, но для чего он в данный момент нужен, я тоже не знаю

2021-05-24 10:49 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    @GetMapping
так а зачем ты его создал?

2021-05-24 10:49 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    private final ObjectSerialization serialization;
ага, кажется понял

2021-05-24 10:53 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/entity/AccountEntity.java
> +    public String toString() {
можно для дебага. логировать действия. но сейчас я думаю, что достаточно будет email , а остальные поля не стоит выводить.

2021-05-24 10:54 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/controller/AccountController.java
> +    @GetMapping
я вспомнил зачем, это был первый метод в классе, я с помощью его получал админа, который сразу есть в бд. надо будет удалить

2021-05-24 14:05 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public Account create(String email, String password) {
это чтобы выполнился откат при ошибке? на все методы, которые вносят изменения в бд следует вешать эту аннотацию.
а транзакции не включены по умолчанию для spring data or spring jdbc например?

2021-05-24 14:09 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/controller/ControllerExceptionHandler.java
> +    @ResponseBody
ErrorResponse как Exception? и уже его выбрасывать в контроллерах вместо исключений из сервисов?

2021-05-24 14:12 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public AccountEntity getAccountByEmail(String email) throws SearchException {
возвращать Optional и из репозитория и из сервиса?

2021-05-24 14:12 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public AccountEntity getAccountByEmail(String email) throws SearchException {
сервису не стоит бросать исключения вообще?

2021-05-25 07:19 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/controller/ControllerExceptionHandler.java
> +    @ResponseBody
Нет, вместо msg, возвращать объект типа ErrorResponse

2021-05-25 07:20 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public Account create(String email, String password) {
включены, но транзакции ставятся над методами сервиса

2021-05-25 07:22 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public AccountEntity getAccountByEmail(String email) throws SearchException {
Optional, можешь и там, и там.
да, 
только в случае пробрасывания исключений с уровня ниже

2021-05-26 10:35 UTC, s-konanau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public Account create(String email, String password) {
а какой надо org.springframework.transaction.annotation.Transactional или javax.transaction.Transactional

2021-05-26 12:47 UTC, artsiom-kotau commented on src/main/java/com/itechart/stock_feed/service/AccountService.java
> +    public Account create(String email, String password) {
spring

2021-05-27 06:59 UTC, artsiom-kotau approved these changes

2021-05-27 07:05 UTC, merged